In [1]:
import numpy as np

In [46]:
data = np.full((5,5), 1)
data[1:-1,1:-1] = 0
print(data)





[[1 1 1 1 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 1 1 1 1]]


In [9]:
"""To Roman"""
roman_dict = {1:"I", 5:"V", 10: "X", 50:"L", 100:"C", 500:"D", 1000:"M"}

def to_roman(num: int) -> str:
    roman_str = ""
    if num > 1000:
        ans, rem = divmod(num, 1000)
        roman_str += ans * roman_dict[1000]
        return roman_str + to_roman(rem)
    if num >= 900:
        rem = num - 900
        roman_str += 'CM'
        return roman_str + to_roman(rem)
    if num >= 500:
        rem = num - 500
        roman_str += "D"
        return roman_str + to_roman(rem)
    if num >= 400:
        rem = num - 400
        roman_str += "CD"
        return roman_str + to_roman(rem)
    if num >= 100:
        ans, rem = divmod(num,100)
        roman_str += ans * "C"
        return roman_str + to_roman(rem)
    return roman_str

to_roman(3700)

'MMMDCC'

In [6]:
import uuid

str(uuid.uuid4())

'be9bb651-b4ff-489c-85e9-0613c384f4f9'